"""Initial schema

Revision ID: 94fa724aefca
Revises:
Create Date: 2026-03-27 13:37:49.895941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fa724aefca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'embeddings' not in existing_tables:
        op.create_table('embeddings',
                        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                        sa.Column('user_name', sa.String(), nullable=True),
                        sa.Column('collection', sa.String(), nullable=True),
                        sa.Column('source_id', sa.String(), nullable=True),
                        sa.Column('text_content', sa.Text(), nullable=False),
                        sa.Column('embedding_json', sa.Text(), nullable=False),
                        sa.PrimaryKeyConstraint('id')
                        )
        op.create_index(op.f('ix_embeddings_collection'), 'embeddings', ['collection'], unique=False)
        op.create_index(op.f('ix_embeddings_source_id'), 'embeddings', ['source_id'], unique=False)
        op.create_index(op.f('ix_embeddings_user_name'), 'embeddings', ['user_name'], unique=False)

    if 'entities' not in existing_tables:
        op.create_table('entities',
                        sa.Column('id', sa.String(length=64), nullable=False),
                        sa.Column('user_name', sa.String(), nullable=True),
                        sa.Column('name', sa.String(), nullable=True),
                        sa.Column('topic', sa.String(), nullable=True),
                        sa.Column('text', sa.String(), nullable=False),
                        sa.Column('tags_json', sa.Text(), nullable=True),
                        sa.PrimaryKeyConstraint('id')
                        )
        op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
        op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
        op.create_index(op.f('ix_entities_topic'), 'entities', ['topic'], unique=False)
        op.create_index(op.f('ix_entities_user_name'), 'entities', ['user_name'], unique=False)

    if 'edges' not in existing_tables:
        op.create_table('edges',
                        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                        sa.Column('user_name', sa.String(), nullable=True),
                        sa.Column('source_id', sa.String(length=64), nullable=True),
                        sa.Column('target_id', sa.String(length=64), nullable=True),
                        sa.Column('source_name', sa.String(), nullable=True),
                        sa.Column('target_name', sa.String(), nullable=True),
                        sa.Column('relation', sa.String(length=255), nullable=True),
                        sa.ForeignKeyConstraint(['source_id'], ['entities.id'], ondelete='CASCADE'),
                        sa.ForeignKeyConstraint(['target_id'], ['entities.id'], ondelete='CASCADE'),
                        sa.PrimaryKeyConstraint('id')
                        )
        op.create_index(op.f('ix_edges_source_name'), 'edges', ['source_name'], unique=False)
        op.create_index(op.f('ix_edges_target_name'), 'edges', ['target_name'], unique=False)
        op.create_index(op.f('ix_edges_user_name'), 'edges', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edges_user_name'), table_name='edges')
    op.drop_index(op.f('ix_edges_target_name'), table_name='edges')
    op.drop_index(op.f('ix_edges_source_name'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_entities_user_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_topic'), table_name='entities')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_embeddings_user_name'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_source_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_collection'), table_name='embeddings')
    op.drop_table('embeddings')
    # ### end Alembic commands ###
